import Navbar from "@/components/Navbar";
import "@/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
 
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Menu from "@/components/Menu";
import { Suspense } from "react";
import Loading from "./components/LoadingContext";
 
const inter = Inter({ subsets: ["latin"] });
 
export const metadata: Metadata = {
  title: "Next.js 14 Login Register MongoDB Next-Auth Login Authentication Daisyui Tailwind",
  description: "Generated by create next app",
};
 
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <div className="container mx-auto px-4">
            <Navbar />
            <div className="flex h-screen">
            <Menu />
            <div className="flex-1 overflow-auto p-4">
            <Suspense fallback={<Loading />}>
            {children}
            </Suspense>
          </div>
          </div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}